// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cicd_sensor/attestation/v1alpha1/predicate.proto

package attestationv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Predicate is the body emitted as the in-toto `runtime-trace` v0.1 predicate.
// The outer in-toto Statement is constructed by the signing step (e.g.
// actions/attest), not by cicd-sensor.
type Predicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorLog    *MonitorLog            `protobuf:"bytes,1,opt,name=monitor_log,json=monitorLog,proto3" json:"monitor_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescGZIP(), []int{0}
}

func (x *Predicate) GetMonitorLog() *MonitorLog {
	if x != nil {
		return x.MonitorLog
	}
	return nil
}

// MonitorLog mirrors runtime-trace v0.1 monitorLog. Standard runtime-trace
// fields use plain keys; cicd-sensor extensions use URI keys per spec so
// that generic consumers can ignore unknown schemas while preserving the
// evidence for cicd-sensor-aware consumers.
//
// `v1alpha1` in the package name marks this schema as pre-stable: it may
// change — including breaking changes — based on industry movement and
// feedback. Stable schemas will live under a separate `v1` package.
type MonitorLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       []string               `protobuf:"bytes,1,rep,name=network,proto3" json:"network,omitempty"`
	Detections    []*RuleHitSummary      `protobuf:"bytes,2,rep,name=detections,json=https://cicd-sensor.github.io/detections,proto3" json:"detections,omitempty"`
	Domains       []string               `protobuf:"bytes,3,rep,name=domains,json=https://cicd-sensor.github.io/domains,proto3" json:"domains,omitempty"`
	Result        *string                `protobuf:"bytes,4,opt,name=result,json=https://cicd-sensor.github.io/result,proto3,oneof" json:"result,omitempty"`
	Job           *JobContext            `protobuf:"bytes,5,opt,name=job,json=https://cicd-sensor.github.io/job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorLog) Reset() {
	*x = MonitorLog{}
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorLog) ProtoMessage() {}

func (x *MonitorLog) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorLog.ProtoReflect.Descriptor instead.
func (*MonitorLog) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorLog) GetNetwork() []string {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MonitorLog) GetDetections() []*RuleHitSummary {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *MonitorLog) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *MonitorLog) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *MonitorLog) GetJob() *JobContext {
	if x != nil {
		return x.Job
	}
	return nil
}

// JobContext is the attestation-side job identity + metadata. Defined here
// (not imported from log/v1) so the attestation schema is independent of the
// log envelope schema and can evolve separately.
type JobContext struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Provider     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderHost string                 `protobuf:"bytes,2,opt,name=provider_host,proto3" json:"provider_host,omitempty"`
	ProjectPath  string                 `protobuf:"bytes,3,opt,name=project_path,proto3" json:"project_path,omitempty"`
	JobLink      string                 `protobuf:"bytes,4,opt,name=job_link,proto3" json:"job_link,omitempty"`
	CommitSha    string                 `protobuf:"bytes,5,opt,name=commit_sha,proto3" json:"commit_sha,omitempty"`
	RefName      string                 `protobuf:"bytes,6,opt,name=ref_name,proto3" json:"ref_name,omitempty"`
	Trigger      string                 `protobuf:"bytes,7,opt,name=trigger,proto3" json:"trigger,omitempty"`
	ActorId      string                 `protobuf:"bytes,8,opt,name=actor_id,proto3" json:"actor_id,omitempty"`
	ActorName    string                 `protobuf:"bytes,9,opt,name=actor_name,proto3" json:"actor_name,omitempty"`
	// GitHub only.
	GithubRunId            string `protobuf:"bytes,10,opt,name=github_run_id,proto3" json:"github_run_id,omitempty"`
	GithubJob              string `protobuf:"bytes,11,opt,name=github_job,proto3" json:"github_job,omitempty"`
	GithubRunAttempt       string `protobuf:"bytes,12,opt,name=github_run_attempt,proto3" json:"github_run_attempt,omitempty"`
	GithubRunnerTrackingId string `protobuf:"bytes,13,opt,name=github_runner_tracking_id,proto3" json:"github_runner_tracking_id,omitempty"`
	GithubWorkflowRef      string `protobuf:"bytes,14,opt,name=github_workflow_ref,proto3" json:"github_workflow_ref,omitempty"`
	GithubWorkflowSha      string `protobuf:"bytes,15,opt,name=github_workflow_sha,proto3" json:"github_workflow_sha,omitempty"`
	GithubWorkflow         string `protobuf:"bytes,16,opt,name=github_workflow,proto3" json:"github_workflow,omitempty"`
	// GitLab only.
	GitlabJobId        string `protobuf:"bytes,17,opt,name=gitlab_job_id,proto3" json:"gitlab_job_id,omitempty"`
	GitlabJobName      string `protobuf:"bytes,18,opt,name=gitlab_job_name,proto3" json:"gitlab_job_name,omitempty"`
	GitlabConfigRefUri string `protobuf:"bytes,19,opt,name=gitlab_config_ref_uri,proto3" json:"gitlab_config_ref_uri,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobContext) Reset() {
	*x = JobContext{}
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobContext) ProtoMessage() {}

func (x *JobContext) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobContext.ProtoReflect.Descriptor instead.
func (*JobContext) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescGZIP(), []int{2}
}

func (x *JobContext) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *JobContext) GetProviderHost() string {
	if x != nil {
		return x.ProviderHost
	}
	return ""
}

func (x *JobContext) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *JobContext) GetJobLink() string {
	if x != nil {
		return x.JobLink
	}
	return ""
}

func (x *JobContext) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *JobContext) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *JobContext) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *JobContext) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *JobContext) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *JobContext) GetGithubRunId() string {
	if x != nil {
		return x.GithubRunId
	}
	return ""
}

func (x *JobContext) GetGithubJob() string {
	if x != nil {
		return x.GithubJob
	}
	return ""
}

func (x *JobContext) GetGithubRunAttempt() string {
	if x != nil {
		return x.GithubRunAttempt
	}
	return ""
}

func (x *JobContext) GetGithubRunnerTrackingId() string {
	if x != nil {
		return x.GithubRunnerTrackingId
	}
	return ""
}

func (x *JobContext) GetGithubWorkflowRef() string {
	if x != nil {
		return x.GithubWorkflowRef
	}
	return ""
}

func (x *JobContext) GetGithubWorkflowSha() string {
	if x != nil {
		return x.GithubWorkflowSha
	}
	return ""
}

func (x *JobContext) GetGithubWorkflow() string {
	if x != nil {
		return x.GithubWorkflow
	}
	return ""
}

func (x *JobContext) GetGitlabJobId() string {
	if x != nil {
		return x.GitlabJobId
	}
	return ""
}

func (x *JobContext) GetGitlabJobName() string {
	if x != nil {
		return x.GitlabJobName
	}
	return ""
}

func (x *JobContext) GetGitlabConfigRefUri() string {
	if x != nil {
		return x.GitlabConfigRefUri
	}
	return ""
}

// RuleHitSummary mirrors log.v1.DetectedRuleSummary one-to-one. Per-event
// detail (process tree, payload, event type, timestamp) is intentionally
// omitted; that detail lives in the detection log and would only inflate
// the attestation.
type RuleHitSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RulesetId       *string                `protobuf:"bytes,1,opt,name=ruleset_id,proto3,oneof" json:"ruleset_id,omitempty"`
	RuleId          *string                `protobuf:"bytes,2,opt,name=rule_id,proto3,oneof" json:"rule_id,omitempty"`
	RulesetRevision *string                `protobuf:"bytes,3,opt,name=ruleset_revision,proto3,oneof" json:"ruleset_revision,omitempty"`
	Action          *string                `protobuf:"bytes,4,opt,name=action,proto3,oneof" json:"action,omitempty"`
	Count           *uint32                `protobuf:"varint,5,opt,name=count,proto3,oneof" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleHitSummary) Reset() {
	*x = RuleHitSummary{}
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleHitSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleHitSummary) ProtoMessage() {}

func (x *RuleHitSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleHitSummary.ProtoReflect.Descriptor instead.
func (*RuleHitSummary) Descriptor() ([]byte, []int) {
	return file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescGZIP(), []int{3}
}

func (x *RuleHitSummary) GetRulesetId() string {
	if x != nil && x.RulesetId != nil {
		return *x.RulesetId
	}
	return ""
}

func (x *RuleHitSummary) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *RuleHitSummary) GetRulesetRevision() string {
	if x != nil && x.RulesetRevision != nil {
		return *x.RulesetRevision
	}
	return ""
}

func (x *RuleHitSummary) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *RuleHitSummary) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_cicd_sensor_attestation_v1alpha1_predicate_proto protoreflect.FileDescriptor

const file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDesc = "" +
	"\n" +
	"0cicd_sensor/attestation/v1alpha1/predicate.proto\x12 cicd_sensor.attestation.v1alpha1\x1a\x1bbuf/validate/validate.proto\"Z\n" +
	"\tPredicate\x12M\n" +
	"\vmonitor_log\x18\x01 \x01(\v2,.cicd_sensor.attestation.v1alpha1.MonitorLogR\n" +
	"monitorLog\"\x97\x03\n" +
	"\n" +
	"MonitorLog\x12\x18\n" +
	"\anetwork\x18\x01 \x03(\tR\anetwork\x12n\n" +
	"\n" +
	"detections\x18\x02 \x03(\v20.cicd_sensor.attestation.v1alpha1.RuleHitSummaryR(https://cicd-sensor.github.io/detections\x126\n" +
	"\adomains\x18\x03 \x03(\tR%https://cicd-sensor.github.io/domains\x12^\n" +
	"\x06result\x18\x04 \x01(\tB#\xbaH r\x1eR\x06passedR\bdetectedR\n" +
	"terminatedH\x00R$https://cicd-sensor.github.io/result\x88\x01\x01\x12\\\n" +
	"\x03job\x18\x05 \x01(\v2,.cicd_sensor.attestation.v1alpha1.JobContextR!https://cicd-sensor.github.io/jobB\t\n" +
	"\a_result\"\xe8\x05\n" +
	"\n" +
	"JobContext\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12$\n" +
	"\rprovider_host\x18\x02 \x01(\tR\rprovider_host\x12\"\n" +
	"\fproject_path\x18\x03 \x01(\tR\fproject_path\x12\x1a\n" +
	"\bjob_link\x18\x04 \x01(\tR\bjob_link\x12\x1e\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\n" +
	"commit_sha\x12\x1a\n" +
	"\bref_name\x18\x06 \x01(\tR\bref_name\x12\x18\n" +
	"\atrigger\x18\a \x01(\tR\atrigger\x12\x1a\n" +
	"\bactor_id\x18\b \x01(\tR\bactor_id\x12\x1e\n" +
	"\n" +
	"actor_name\x18\t \x01(\tR\n" +
	"actor_name\x12$\n" +
	"\rgithub_run_id\x18\n" +
	" \x01(\tR\rgithub_run_id\x12\x1e\n" +
	"\n" +
	"github_job\x18\v \x01(\tR\n" +
	"github_job\x12.\n" +
	"\x12github_run_attempt\x18\f \x01(\tR\x12github_run_attempt\x12<\n" +
	"\x19github_runner_tracking_id\x18\r \x01(\tR\x19github_runner_tracking_id\x120\n" +
	"\x13github_workflow_ref\x18\x0e \x01(\tR\x13github_workflow_ref\x120\n" +
	"\x13github_workflow_sha\x18\x0f \x01(\tR\x13github_workflow_sha\x12(\n" +
	"\x0fgithub_workflow\x18\x10 \x01(\tR\x0fgithub_workflow\x12$\n" +
	"\rgitlab_job_id\x18\x11 \x01(\tR\rgitlab_job_id\x12(\n" +
	"\x0fgitlab_job_name\x18\x12 \x01(\tR\x0fgitlab_job_name\x124\n" +
	"\x15gitlab_config_ref_uri\x18\x13 \x01(\tR\x15gitlab_config_ref_uri\"\x9c\x02\n" +
	"\x0eRuleHitSummary\x12#\n" +
	"\n" +
	"ruleset_id\x18\x01 \x01(\tH\x00R\n" +
	"ruleset_id\x88\x01\x01\x12\x1d\n" +
	"\arule_id\x18\x02 \x01(\tH\x01R\arule_id\x88\x01\x01\x12/\n" +
	"\x10ruleset_revision\x18\x03 \x01(\tH\x02R\x10ruleset_revision\x88\x01\x01\x125\n" +
	"\x06action\x18\x04 \x01(\tB\x18\xbaH\x15r\x13R\x06detectR\tterminateH\x03R\x06action\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x05 \x01(\rH\x04R\x05count\x88\x01\x01B\r\n" +
	"\v_ruleset_idB\n" +
	"\n" +
	"\b_rule_idB\x13\n" +
	"\x11_ruleset_revisionB\t\n" +
	"\a_actionB\b\n" +
	"\x06_countB\xbc\x02\n" +
	"$com.cicd_sensor.attestation.v1alpha1B\x0ePredicateProtoP\x01Zfgithub.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/attestation/v1alpha1;attestationv1alpha1\xa2\x02\x03CAX\xaa\x02\x1fCicdSensor.Attestation.V1alpha1\xca\x02\x1fCicdSensor\\Attestation\\V1alpha1\xe2\x02+CicdSensor\\Attestation\\V1alpha1\\GPBMetadata\xea\x02!CicdSensor::Attestation::V1alpha1b\x06proto3"

var (
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescOnce sync.Once
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescData []byte
)

func file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescGZIP() []byte {
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescOnce.Do(func() {
		file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDesc), len(file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDesc)))
	})
	return file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDescData
}

var file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cicd_sensor_attestation_v1alpha1_predicate_proto_goTypes = []any{
	(*Predicate)(nil),      // 0: cicd_sensor.attestation.v1alpha1.Predicate
	(*MonitorLog)(nil),     // 1: cicd_sensor.attestation.v1alpha1.MonitorLog
	(*JobContext)(nil),     // 2: cicd_sensor.attestation.v1alpha1.JobContext
	(*RuleHitSummary)(nil), // 3: cicd_sensor.attestation.v1alpha1.RuleHitSummary
}
var file_cicd_sensor_attestation_v1alpha1_predicate_proto_depIdxs = []int32{
	1, // 0: cicd_sensor.attestation.v1alpha1.Predicate.monitor_log:type_name -> cicd_sensor.attestation.v1alpha1.MonitorLog
	3, // 1: cicd_sensor.attestation.v1alpha1.MonitorLog.detections:type_name -> cicd_sensor.attestation.v1alpha1.RuleHitSummary
	2, // 2: cicd_sensor.attestation.v1alpha1.MonitorLog.job:type_name -> cicd_sensor.attestation.v1alpha1.JobContext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cicd_sensor_attestation_v1alpha1_predicate_proto_init() }
func file_cicd_sensor_attestation_v1alpha1_predicate_proto_init() {
	if File_cicd_sensor_attestation_v1alpha1_predicate_proto != nil {
		return
	}
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[1].OneofWrappers = []any{}
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDesc), len(file_cicd_sensor_attestation_v1alpha1_predicate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cicd_sensor_attestation_v1alpha1_predicate_proto_goTypes,
		DependencyIndexes: file_cicd_sensor_attestation_v1alpha1_predicate_proto_depIdxs,
		MessageInfos:      file_cicd_sensor_attestation_v1alpha1_predicate_proto_msgTypes,
	}.Build()
	File_cicd_sensor_attestation_v1alpha1_predicate_proto = out.File
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_goTypes = nil
	file_cicd_sensor_attestation_v1alpha1_predicate_proto_depIdxs = nil
}
