package report

import (
	"bytes"
	"cmp"
	"fmt"
	"html/template"
	"io"
	"maps"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/cicd-sensor/cicd-sensor/internal/resultdoc"
)

const (
	StepSummaryHeaderDetected   = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-detected.svg"
	StepSummaryHeaderPassed     = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-passed.svg"
	StepSummaryHeaderTerminated = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-terminated.svg"

	stepSummaryTopN         = 5
	stepSummaryProcessLimit = 5
)

// StepSummaryOptions carries pre-validated URLs and flags from the CLI.
// URL trust validation is the caller's responsibility.
type StepSummaryOptions struct {
	HTMLURL      string
	HealthFailed bool
}

var stepSummaryTemplate = template.Must(template.New("stepsummary").Parse(`<hr />
{{if .HeaderLink}}<a href="{{.HeaderLink}}">{{end}}<img src="{{.HeaderURL}}" width="650" alt="cicd-sensor - {{.OverallResult}}" />{{if .HeaderLink}}</a>{{end}}
{{if .HealthFailed}}<p>Agent health check failed during the post step. Counts and rule hits are unavailable for this run.</p>
{{end}}{{if .RuleHits}}<h3>Top 5 rule matches</h3>
<ul>
{{range .RuleHits}}<li>{{.Emoji}} <code>{{.RuleID}}</code>{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#hits">Details</a>{{end}} — <strong>{{.Count}}</strong>{{template "processes" .}}</li>
{{end}}</ul>
{{end}}{{if .Domains}}<h3>Top 5 domain observations</h3>
<ul>
{{range .Domains}}<li><code>{{.Domain}}</code>{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#domains">Details</a>{{end}} — <strong>{{.Count}}</strong>{{template "processes" .}}</li>
{{end}}</ul>
{{end}}{{if .Networks}}<h3>Top 5 network connections</h3>
<ul>
{{range .Networks}}<li><code>{{.Endpoint}}</code>{{if .Protocol}} <code>{{.Protocol}}</code>{{end}}{{if $.HTMLURL}} — <a href="{{$.HTMLURL}}#network">Details</a>{{end}} — <strong>{{.Count}}</strong>{{template "processes" .}}</li>
{{end}}</ul>
{{end}}{{if .TimelineURL}}<p>📊 <a href="{{.TimelineURL}}">Or open the full timeline ({{.TotalEvents}} events) →</a></p>
{{end}}<sub>Generated by <a href="https://github.com/cicd-sensor/cicd-sensor">cicd-sensor</a></sub>
<hr />
{{define "processes"}}{{if .Processes}} · {{range $i, $p := .Processes}}{{if $i}}, {{end}}<code>{{$p}}</code>{{end}}{{if .ProcessOverflow}}, +{{.ProcessOverflow}} more{{end}}{{end}}{{end}}`))

type stepSummaryView struct {
	OverallResult string
	HeaderURL     string
	HeaderLink    string
	HTMLURL       string
	HealthFailed  bool
	RuleHits      []stepSummaryRuleHit
	Domains       []stepSummaryDomain
	Networks      []stepSummaryNetwork
	TimelineURL   string
	TotalEvents   int
}

type stepSummaryRuleHit struct {
	RuleID          string
	Emoji           string
	Count           int
	Processes       []string
	ProcessOverflow int
}

type stepSummaryDomain struct {
	Domain          string
	Count           int
	Processes       []string
	ProcessOverflow int
}

type stepSummaryNetwork struct {
	Endpoint        string
	Protocol        string
	Count           int
	Processes       []string
	ProcessOverflow int
}

// RenderStepSummary writes the GitHub Step Summary HTML for result to w.
func RenderStepSummary(w io.Writer, result resultdoc.JobEventSummaryForReport, opts StepSummaryOptions) error {
	overallResult := resultdoc.ResultPassed
	if opts.HealthFailed {
		overallResult = "health_failed"
	} else {
		switch result.ResultSummary.Result {
		case resultdoc.ResultPassed, resultdoc.ResultDetected, resultdoc.ResultTerminated:
			overallResult = result.ResultSummary.Result
		}
	}

	view := stepSummaryView{
		OverallResult: overallResult,
		HeaderURL:     stepSummaryHeaderURL(overallResult),
		HeaderLink:    opts.HTMLURL,
		HTMLURL:       opts.HTMLURL,
		HealthFailed:  opts.HealthFailed,
	}
	if !opts.HealthFailed {
		view.RuleHits = topStepSummaryRuleHits(result.Hits, stepSummaryTopN)
		view.Domains = topStepSummaryDomains(result.DomainObservations, stepSummaryTopN)
		view.Networks = topStepSummaryNetworks(result.NetworkConnections, stepSummaryTopN)
		view.TotalEvents = totalAlertEvents(result.Hits) + len(result.DomainObservations) + len(result.NetworkConnections)
		if opts.HTMLURL != "" && view.TotalEvents > 0 {
			view.TimelineURL = opts.HTMLURL + "#hits"
		}
	}

	var out bytes.Buffer
	if err := stepSummaryTemplate.Execute(&out, view); err != nil {
		return fmt.Errorf("render step summary: %w", err)
	}
	_, err := w.Write(out.Bytes())
	return err
}

func topStepSummaryRuleHits(hits []resultdoc.HitRecord, limit int) []stepSummaryRuleHit {
	out := make([]stepSummaryRuleHit, 0, len(hits))
	for _, h := range hits {
		if h.Action != "detect" && h.Action != "terminate" {
			continue
		}
		procs := map[string]struct{}{}
		for _, e := range h.AlertEvents {
			if e.Process != nil {
				addStepSummaryProcess(procs, e.Process.ExecPath)
			}
		}
		processes, overflow := stepSummaryProcesses(procs)
		out = append(out, stepSummaryRuleHit{
			RuleID:          stepSummaryDisplayText(h.RuleID, 64, "unknown"),
			Emoji:           stepSummaryActionEmoji(h.Action),
			Count:           int(h.HitCount),
			Processes:       processes,
			ProcessOverflow: overflow,
		})
	}
	slices.SortFunc(out, func(a, b stepSummaryRuleHit) int {
		return cmp.Or(
			cmp.Compare(b.Count, a.Count),   // count desc
			cmp.Compare(a.RuleID, b.RuleID), // ruleID asc
		)
	})
	return out[:min(limit, len(out))]
}

func totalAlertEvents(hits []resultdoc.HitRecord) int {
	n := 0
	for _, h := range hits {
		n += len(h.AlertEvents)
	}
	return n
}

func topStepSummaryDomains(observations []resultdoc.DomainObservation, limit int) []stepSummaryDomain {
	type group struct {
		domain    string
		count     int
		processes map[string]struct{}
	}
	groups := make(map[string]*group)
	for _, observation := range observations {
		domain := stepSummaryDisplayText(displayDomain(observation.Domain), 96, "unknown")
		g := groups[domain]
		if g == nil {
			g = &group{domain: domain, processes: make(map[string]struct{})}
			groups[domain] = g
		}
		g.count += len(observation.Processes)
		for _, process := range observation.Processes {
			addStepSummaryProcess(g.processes, process.ExecPath)
		}
	}

	ordered := slices.Collect(maps.Values(groups))
	slices.SortFunc(ordered, func(a, b *group) int {
		return cmp.Or(
			cmp.Compare(b.count, a.count),
			cmp.Compare(a.domain, b.domain),
		)
	})

	out := make([]stepSummaryDomain, 0, min(limit, len(ordered)))
	for _, g := range ordered[:min(limit, len(ordered))] {
		processes, overflow := stepSummaryProcesses(g.processes)
		out = append(out, stepSummaryDomain{
			Domain:          g.domain,
			Count:           g.count,
			Processes:       processes,
			ProcessOverflow: overflow,
		})
	}
	return out
}

func topStepSummaryNetworks(connections []resultdoc.NetworkConnection, limit int) []stepSummaryNetwork {
	type group struct {
		endpoint  string
		protocol  string
		count     int
		processes map[string]struct{}
	}
	groups := make(map[string]*group)
	for _, connection := range connections {
		protocol := strings.ToUpper(stepSummaryDisplayText(connection.Protocol, 12, ""))
		endpoint := stepSummaryEndpoint(connection.RemoteIP, connection.RemotePort)
		key := endpoint + "\x00" + protocol
		g := groups[key]
		if g == nil {
			g = &group{endpoint: endpoint, protocol: protocol, processes: make(map[string]struct{})}
			groups[key] = g
		}
		g.count += len(connection.Processes)
		for _, process := range connection.Processes {
			addStepSummaryProcess(g.processes, process.ExecPath)
		}
	}

	ordered := slices.Collect(maps.Values(groups))
	slices.SortFunc(ordered, func(a, b *group) int {
		return cmp.Or(
			cmp.Compare(b.count, a.count),
			cmp.Compare(a.endpoint, b.endpoint),
			cmp.Compare(a.protocol, b.protocol),
		)
	})

	out := make([]stepSummaryNetwork, 0, min(limit, len(ordered)))
	for _, g := range ordered[:min(limit, len(ordered))] {
		processes, overflow := stepSummaryProcesses(g.processes)
		out = append(out, stepSummaryNetwork{
			Endpoint:        g.endpoint,
			Protocol:        g.protocol,
			Count:           g.count,
			Processes:       processes,
			ProcessOverflow: overflow,
		})
	}
	return out
}

func stepSummaryProcesses(processes map[string]struct{}) ([]string, int) {
	ordered := slices.Sorted(maps.Keys(processes))
	if len(ordered) <= stepSummaryProcessLimit {
		return ordered, 0
	}
	return ordered[:stepSummaryProcessLimit], len(ordered) - stepSummaryProcessLimit
}

func addStepSummaryProcess(processes map[string]struct{}, execPath string) {
	process := stepSummaryProcessName(execPath)
	if process == "" {
		return
	}
	processes[process] = struct{}{}
}

func stepSummaryProcessName(execPath string) string {
	if i := strings.LastIndexAny(execPath, `/\`); i >= 0 && i+1 < len(execPath) {
		execPath = execPath[i+1:]
	}
	return stepSummaryDisplayText(execPath, 48, "")
}

func stepSummaryEndpoint(remoteIP string, remotePort int64) string {
	ip := stepSummaryDisplayText(remoteIP, 80, "unknown")
	if remotePort <= 0 {
		return ip
	}
	if strings.Contains(ip, ":") && !strings.HasPrefix(ip, "[") {
		ip = "[" + ip + "]"
	}
	return ip + ":" + strconv.FormatInt(remotePort, 10)
}

// Truncates to maxRunes for layout / resource protection. Empty input gets
// the fallback placeholder. Other input is trusted as-is.
func stepSummaryDisplayText(value string, maxRunes int, fallback string) string {
	if value == "" {
		return fallback
	}
	if utf8.RuneCountInString(value) <= maxRunes {
		return value
	}
	runes := []rune(value)
	if maxRunes <= 3 {
		return string(runes[:maxRunes])
	}
	return string(runes[:maxRunes-3]) + "..."
}

func stepSummaryActionEmoji(action string) string {
	if action == "terminate" {
		return "🛑"
	}
	return "⚠️"
}

func stepSummaryHeaderURL(overallResult string) string {
	switch overallResult {
	case resultdoc.ResultDetected:
		return StepSummaryHeaderDetected
	case resultdoc.ResultTerminated, "health_failed":
		return StepSummaryHeaderTerminated
	default:
		return StepSummaryHeaderPassed
	}
}
