package main

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/cicd-sensor/cicd-sensor/internal/ctl/report"
	"github.com/cicd-sensor/cicd-sensor/internal/resultdoc"
)

func TestRunReportStepSummary_StdinHappyPath(t *testing.T) {
	t.Parallel()

	sample := sampleProjectResult()
	sample.Hits[0].RuleID = "]((https://evil.example))"
	sample.Hits[0].RuleCondition = "![evil](https://evil.example)"
	sample.Hits[0].AlertEvents[0].Process = &resultdoc.ProcessSummary{ExecPath: "<script>alert(1)"}
	// IDN homograph: Cyrillic "а" instead of Latin "a". IDNA should expose
	// this as an xn--… Punycode label.
	sample.DomainObservations[0].Domain = "evil.exаmple"
	sample.DomainObservations[0].Processes = []resultdoc.ObservationProcess{{ExecPath: "<script>domain()"}}
	sample.NetworkConnections[0].Processes = []resultdoc.ObservationProcess{{ExecPath: "/usr/bin/curl"}}
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--html-url", "https://github.com/acme/project/actions/runs/1/artifacts/2",
	}, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}

	got := stdout.String()
	for _, want := range []string{
		report.StepSummaryHeaderDetected,
		`width="650"`,
		`<h3>Top 5 rule matches</h3>`,
		`<li>`,
		`<code>]((https://evil.example))</code>`,
		// Homograph domain surfaces as xn--… via IDNA.
		`<code>evil.xn--exmple-4nf</code>`,
		`<code>8.8.8.8:443</code> <code>TCP</code>`,
		`<code>&lt;script&gt;alert(1)</code>`,
		`<code>&lt;script&gt;domain()</code>`,
		`<a href="https://github.com/acme/project/actions/runs/1/artifacts/2#hits">Details</a>`,
		`<strong>1</strong>`,
		`Generated by`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in output:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{
		"rule_condition",
		"![evil]",
		`](https://evil.example)`,
		"<script>",
		"### ",
		"**1**",
		// Raw Cyrillic must not appear — IDNA should have converted it.
		"evil.exаmple",
	} {
		if strings.Contains(got, unwanted) {
			t.Fatalf("summary rendered untrusted result detail %q:\n%s", unwanted, got)
		}
	}
}

func TestRunReportStepSummary_TopFiveSummaries(t *testing.T) {
	t.Parallel()

	sample := sampleProjectResult()
	sample.Hits = nil
	for i := range 6 {
		ruleID := "rule-" + string(rune('a'+i))
		sample.Hits = append(sample.Hits, resultdoc.HitRecord{
			RuleID:   ruleID,
			Action:   "detect",
			HitCount: 1,
			AlertEvents: []resultdoc.AlertEvent{{
				Process: &resultdoc.ProcessSummary{ExecPath: "/usr/bin/process-" + string(rune('a'+i))},
			}},
		})
	}
	sample.Hits = append(sample.Hits, resultdoc.HitRecord{
		RuleID: "rule-hot", Action: "terminate", HitCount: 2,
		AlertEvents: []resultdoc.AlertEvent{
			{Process: &resultdoc.ProcessSummary{ExecPath: `C:\Windows\System32\cmd.exe`}},
			{Process: &resultdoc.ProcessSummary{ExecPath: "/usr/bin/bash"}},
		},
	})
	sample.DomainObservations = []resultdoc.DomainObservation{{
		Domain: "very-long-domain-name.example",
		Processes: []resultdoc.ObservationProcess{
			{ExecPath: "/usr/bin/getent"},
			{ExecPath: "/usr/bin/node"},
		},
	}}
	sample.NetworkConnections = []resultdoc.NetworkConnection{{
		RemoteIP:   "2606:4700::6810:122",
		RemotePort: 443,
		Protocol:   "udp",
		Processes:  []resultdoc.ObservationProcess{{ExecPath: "/usr/bin/node"}},
	}}
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--html-url", "https://github.com/acme/project/actions/runs/1/artifacts/2",
	}, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}

	got := stdout.String()
	for _, want := range []string{
		`<h3>Top 5 rule matches</h3>`,
		`<li>🛑 <code>rule-hot</code>`,
		`<code>cmd.exe</code>`,
		`<h3>Top 5 domain observations</h3>`,
		`<code>very-long-domain-name.example</code>`,
		`<h3>Top 5 network connections</h3>`,
		`<code>[2606:4700::6810:122]:443</code> <code>UDP</code>`,
		`full timeline (10 events)`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in output:\n%s", want, got)
		}
	}
	if strings.Contains(got, "rule-f") {
		t.Fatalf("expected only top 5 rule groups, got:\n%s", got)
	}
}

func TestRunReportStepSummary_OmitsCollectOnlyRules(t *testing.T) {
	t.Parallel()

	sample := sampleProjectResult()
	sample.Hits = []resultdoc.HitRecord{
		{RuleID: "collect-only-rule", Action: "collect", HitCount: 2, AlertEvents: []resultdoc.AlertEvent{
			{Process: &resultdoc.ProcessSummary{ExecPath: "/usr/bin/curl"}},
			{Process: &resultdoc.ProcessSummary{ExecPath: "/usr/bin/curl"}},
		}},
		{RuleID: "detect-rule", Action: "detect", HitCount: 1, AlertEvents: []resultdoc.AlertEvent{
			{Process: &resultdoc.ProcessSummary{ExecPath: "/usr/bin/node"}},
		}},
	}
	sample.DomainObservations = nil
	sample.NetworkConnections = nil
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), nil, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if strings.Contains(got, "collect-only-rule") {
		t.Fatalf("collect-only rule must not appear in top matches:\n%s", got)
	}
	if !strings.Contains(got, "<code>detect-rule</code>") {
		t.Fatalf("detect rule must appear in top matches:\n%s", got)
	}
}

func TestRunReportStepSummary_ResultHeaders(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		result string
		want   string
	}{
		{name: "passed", result: resultdoc.ResultPassed, want: report.StepSummaryHeaderPassed},
		{name: "detected", result: resultdoc.ResultDetected, want: report.StepSummaryHeaderDetected},
		{name: "terminated", result: resultdoc.ResultTerminated, want: report.StepSummaryHeaderTerminated},
		{name: "unknown falls back to passed", result: "javascript:alert(1)", want: report.StepSummaryHeaderPassed},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			sample := sampleProjectResult()
			sample.ResultSummary.Result = tt.result
			body, err := json.Marshal(sample)
			if err != nil {
				t.Fatalf("marshal sample: %v", err)
			}

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), nil, bytes.NewReader(body), &stdout, &stderr)
			if err != nil {
				t.Fatalf("runReportStepSummary: %v", err)
			}
			if code != 0 {
				t.Fatalf("exit code: got %d, want 0", code)
			}
			if !strings.Contains(stdout.String(), tt.want) {
				t.Fatalf("output:\n%s\nwant header %s", stdout.String(), tt.want)
			}
		})
	}
}

func TestRunReportStepSummary_HealthFailedWithoutInput(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--health-failed",
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if !strings.Contains(got, report.StepSummaryHeaderTerminated) {
		t.Fatalf("missing health failure header:\n%s", got)
	}
	if !strings.Contains(got, "Agent health check failed during the post step") {
		t.Fatalf("missing health failure message:\n%s", got)
	}
}

func TestRunReportStepSummary_HealthFailedOverridesResult(t *testing.T) {
	t.Parallel()

	sample := sampleProjectResult()
	sample.ResultSummary.Result = resultdoc.ResultDetected
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{"--health-failed"}, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if !strings.Contains(got, report.StepSummaryHeaderTerminated) {
		t.Fatalf("missing health failure header:\n%s", got)
	}
	if strings.Contains(got, report.StepSummaryHeaderDetected) {
		t.Fatalf("health failure should override detected result:\n%s", got)
	}
}

func TestRunReportStepSummary_TemplateEscapesURLAttributes(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--html-url", `https://github.com/acme/project/actions/runs/1/artifacts/2?x=1&y=%22%3E%3Cscript%3Ealert(1)%3C/script%3E`,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if strings.Contains(got, `""><script>`) || strings.Contains(got, "<script>") {
		t.Fatalf("URL attribute was not safely escaped:\n%s", got)
	}
	want := `x=1&amp;y=%22%3E%3Cscript%3Ealert%281%29%3C/script%3E`
	if !strings.Contains(got, want) {
		t.Fatalf("missing escaped URL fragment %q in:\n%s", want, got)
	}
}

func TestRunReportStepSummary_InvalidURL(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want string
	}{
		{name: "javascript", args: []string{"--html-url", "javascript:alert(1)"}, want: "unsupported scheme"},
		{name: "missing host", args: []string{"--html-url", "https:///missing-host"}, want: "missing host"},
		{name: "malformed", args: []string{"--html-url", "https://[::1"}, want: "missing ']'"},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), tt.args, strings.NewReader(""), &stdout, &stderr)
			if code != 1 {
				t.Fatalf("exit code: got %d, want 1", code)
			}
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error: got %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestRunReportStepSummary_InvalidInputAndUsage(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		args     []string
		input    string
		wantCode int
		wantErr  string
	}{
		{name: "invalid JSON", input: "not json", wantCode: 1, wantErr: "decode project result"},
		{name: "unknown flag", args: []string{"--bogus"}, wantCode: 2, wantErr: "flag provided but not defined"},
		{name: "too many args", args: []string{"extra"}, wantCode: 2, wantErr: "too many arguments"},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), tt.args, strings.NewReader(tt.input), &stdout, &stderr)
			if code != tt.wantCode {
				t.Fatalf("exit code: got %d, want %d", code, tt.wantCode)
			}
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Fatalf("error: got %v, want containing %q", err, tt.wantErr)
			}
		})
	}
}

func TestRunReportStepSummary_Help(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{"-h"}, nil, &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: got error %v, want nil", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout: got %q, want empty", stdout.String())
	}
	for _, want := range []string{
		"usage: cicd-sensorctl report stepsummary [flags]",
		"--html-url",
		"--health-failed",
	} {
		if !strings.Contains(stderr.String(), want) {
			t.Fatalf("stderr: got %q, want substring %q", stderr.String(), want)
		}
	}
}
