package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"html/template"
	"io"
	"net/url"

	"github.com/cicd-sensor/cicd-sensor/internal/resultdoc"
)

const (
	stepSummaryHeaderDetected   = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-detected.svg"
	stepSummaryHeaderNoAlert    = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-no-alert.svg"
	stepSummaryHeaderTerminated = "https://raw.githubusercontent.com/cicd-sensor/cicd-sensor-action/refs/heads/main/assets/header-terminate.svg"
)

var stepSummaryTemplate = template.Must(template.New("stepsummary").Parse(`<hr />

{{if .HeaderLink}}<a href="{{.HeaderLink}}">{{end}}<img src="{{.HeaderURL}}" width="920" alt="cicd-sensor - {{.Verdict}}" />{{if .HeaderLink}}</a>{{end}}

{{if .HealthFailed}}Agent health check failed during the post step. Counts and rule hits are unavailable for this run.

{{end}}{{if .HTMLURL}}<a href="{{.HTMLURL}}#hits">Open the full cicd-sensor report</a>

{{end}}{{if .DebugURL}}<a href="{{.DebugURL}}">Open the cicd-sensor debug bundle</a>

{{end}}<sub>Generated by <a href="https://github.com/cicd-sensor/cicd-sensor">cicd-sensor</a></sub>

<hr />
`))

type reportStepSummaryOptions struct {
	htmlURL      string
	debugURL     string
	healthFailed bool
	help         bool
}

type stepSummaryView struct {
	Verdict      string
	HeaderURL    string
	HeaderLink   string
	HTMLURL      string
	DebugURL     string
	HealthFailed bool
}

// runReportStepSummary renders GitHub Step Summary Markdown for cicd-sensor-action.
func runReportStepSummary(_ context.Context, args []string, stdin io.Reader, stdout, stderr io.Writer) (int, error) {
	opts, err := parseReportStepSummaryArgs(args, stderr)
	if err != nil {
		return 2, err
	}
	if opts.help {
		return 0, nil
	}

	var input []byte
	if stdin != nil {
		input, err = readReportInput(stdin)
		if err != nil {
			return 1, fmt.Errorf("read input: %w", err)
		}
	}

	var resultLog resultdoc.JobEventSummaryForReport
	if len(bytes.TrimSpace(input)) > 0 {
		if err := json.Unmarshal(input, &resultLog); err != nil {
			return 1, fmt.Errorf("decode job_result_log: %w", err)
		}
	}

	body, err := renderStepSummaryMarkdown(resultLog, opts)
	if err != nil {
		return 1, err
	}
	if _, err := stdout.Write(body); err != nil {
		return 1, fmt.Errorf("write stdout: %w", err)
	}
	return 0, nil
}

func parseReportStepSummaryArgs(args []string, stderr io.Writer) (reportStepSummaryOptions, error) {
	var opts reportStepSummaryOptions
	fs := flag.NewFlagSet("report stepsummary", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.Usage = func() {
		fmt.Fprintln(fs.Output(), "usage: cicd-sensorctl report stepsummary [flags]")
		fmt.Fprintln(fs.Output())
		fmt.Fprintln(fs.Output(), "Input:")
		fmt.Fprintln(fs.Output(), "  Reads job_result_log JSON from stdin when available.")
		fmt.Fprintln(fs.Output())
		fmt.Fprintln(fs.Output(), "Optional:")
		fmt.Fprintln(fs.Output(), "  --html-url URL")
		fmt.Fprintln(fs.Output(), "        Trusted URL for the uploaded HTML report artifact.")
		fmt.Fprintln(fs.Output(), "  --debug-url URL")
		fmt.Fprintln(fs.Output(), "        Trusted URL for the uploaded debug artifact.")
		fmt.Fprintln(fs.Output(), "  --health-failed")
		fmt.Fprintln(fs.Output(), "        Render an agent health-failure summary.")
	}
	fs.StringVar(&opts.htmlURL, "html-url", "", "Trusted URL for the HTML report artifact.")
	fs.StringVar(&opts.debugURL, "debug-url", "", "Trusted URL for the debug artifact.")
	fs.BoolVar(&opts.healthFailed, "health-failed", false, "Render health-failure summary.")
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			opts.help = true
			return opts, nil
		}
		return opts, err
	}
	if fs.NArg() != 0 {
		return opts, newUsageError(2, "report stepsummary: too many arguments")
	}
	return opts, nil
}

func renderStepSummaryMarkdown(resultLog resultdoc.JobEventSummaryForReport, opts reportStepSummaryOptions) ([]byte, error) {
	htmlURL, err := trustedStepSummaryURL(opts.htmlURL)
	if err != nil {
		return nil, fmt.Errorf("html-url: %w", err)
	}
	debugURL, err := trustedStepSummaryURL(opts.debugURL)
	if err != nil {
		return nil, fmt.Errorf("debug-url: %w", err)
	}

	verdict := resultdoc.ResultNoAlert
	if opts.healthFailed {
		verdict = "health_failed"
	} else {
		switch resultLog.ResultSummary.Result {
		case resultdoc.ResultNoAlert, resultdoc.ResultDetected, resultdoc.ResultTerminated:
			verdict = resultLog.ResultSummary.Result
		}
	}

	view := stepSummaryView{
		Verdict:      verdict,
		HeaderURL:    stepSummaryHeaderURL(verdict),
		HeaderLink:   htmlURL,
		HTMLURL:      htmlURL,
		DebugURL:     debugURL,
		HealthFailed: opts.healthFailed,
	}

	var out bytes.Buffer
	if err := stepSummaryTemplate.Execute(&out, view); err != nil {
		return nil, fmt.Errorf("render step summary: %w", err)
	}
	return out.Bytes(), nil
}

func stepSummaryHeaderURL(verdict string) string {
	switch verdict {
	case resultdoc.ResultDetected:
		return stepSummaryHeaderDetected
	case resultdoc.ResultTerminated, "health_failed":
		return stepSummaryHeaderTerminated
	default:
		return stepSummaryHeaderNoAlert
	}
}

func trustedStepSummaryURL(raw string) (string, error) {
	if raw == "" {
		return "", nil
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", err
	}
	if u.Scheme != "https" && u.Scheme != "http" {
		return "", fmt.Errorf("unsupported scheme %q", u.Scheme)
	}
	if u.Host == "" {
		return "", fmt.Errorf("missing host")
	}
	return u.String(), nil
}
