package main

import (
	"bytes"
	"context"
	"encoding/json"
	"strings"
	"testing"

	"github.com/cicd-sensor/cicd-sensor/internal/resultdoc"
)

func TestRunReportStepSummary_StdinHappyPath(t *testing.T) {
	t.Parallel()

	sample := sampleResultLog()
	sample.Hits[0].RuleID = "]((https://evil.example))"
	sample.Hits[0].RuleCondition = "![evil](https://evil.example)"
	sample.DomainObservations[0].Domain = "evil.example\n# forged"
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--html-url", "https://github.com/acme/project/actions/runs/1/artifacts/2",
	}, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}

	got := stdout.String()
	for _, want := range []string{
		stepSummaryHeaderDetected,
		`<a href="https://github.com/acme/project/actions/runs/1/artifacts/2#hits">Open the full cicd-sensor report</a>`,
		`Generated by`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing %q in output:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{
		"evil.example",
		"curl-egress",
		"rule_condition",
		"forged",
	} {
		if strings.Contains(got, unwanted) {
			t.Fatalf("summary rendered untrusted result detail %q:\n%s", unwanted, got)
		}
	}
}

func TestRunReportStepSummary_ResultHeaders(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		result string
		want   string
	}{
		{name: "no alert", result: resultdoc.ResultNoAlert, want: stepSummaryHeaderNoAlert},
		{name: "detected", result: resultdoc.ResultDetected, want: stepSummaryHeaderDetected},
		{name: "terminated", result: resultdoc.ResultTerminated, want: stepSummaryHeaderTerminated},
		{name: "unknown falls back to no alert", result: "javascript:alert(1)", want: stepSummaryHeaderNoAlert},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			sample := sampleResultLog()
			sample.ResultSummary.Result = tt.result
			body, err := json.Marshal(sample)
			if err != nil {
				t.Fatalf("marshal sample: %v", err)
			}

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), nil, bytes.NewReader(body), &stdout, &stderr)
			if err != nil {
				t.Fatalf("runReportStepSummary: %v", err)
			}
			if code != 0 {
				t.Fatalf("exit code: got %d, want 0", code)
			}
			if !strings.Contains(stdout.String(), tt.want) {
				t.Fatalf("output:\n%s\nwant header %s", stdout.String(), tt.want)
			}
		})
	}
}

func TestRunReportStepSummary_HealthFailedWithoutInput(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--health-failed",
		"--debug-url", "https://github.com/acme/project/actions/runs/1/artifacts/9",
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if !strings.Contains(got, stepSummaryHeaderTerminated) {
		t.Fatalf("missing health failure header:\n%s", got)
	}
	if !strings.Contains(got, "Agent health check failed during the post step") {
		t.Fatalf("missing health failure message:\n%s", got)
	}
	if !strings.Contains(got, `Open the cicd-sensor debug bundle`) {
		t.Fatalf("missing debug link:\n%s", got)
	}
}

func TestRunReportStepSummary_HealthFailedOverridesResult(t *testing.T) {
	t.Parallel()

	sample := sampleResultLog()
	sample.ResultSummary.Result = resultdoc.ResultDetected
	body, err := json.Marshal(sample)
	if err != nil {
		t.Fatalf("marshal sample: %v", err)
	}

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{"--health-failed"}, bytes.NewReader(body), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if !strings.Contains(got, stepSummaryHeaderTerminated) {
		t.Fatalf("missing health failure header:\n%s", got)
	}
	if strings.Contains(got, stepSummaryHeaderDetected) {
		t.Fatalf("health failure should override detected result:\n%s", got)
	}
}

func TestRunReportStepSummary_TemplateEscapesURLAttributes(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{
		"--html-url", `https://github.com/acme/project/actions/runs/1/artifacts/2?x=1&y=%22%3E%3Cscript%3Ealert(1)%3C/script%3E`,
		"--debug-url", `https://github.com/acme/project/actions/runs/1/artifacts/9?name=a&next=%27`,
	}, strings.NewReader(""), &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: %v", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	got := stdout.String()
	if strings.Contains(got, `""><script>`) || strings.Contains(got, "<script>") {
		t.Fatalf("URL attribute was not safely escaped:\n%s", got)
	}
	for _, want := range []string{
		`x=1&amp;y=%22%3E%3Cscript%3Ealert%281%29%3C/script%3E`,
		`name=a&amp;next=%27`,
	} {
		if !strings.Contains(got, want) {
			t.Fatalf("missing escaped URL fragment %q in:\n%s", want, got)
		}
	}
}

func TestRunReportStepSummary_InvalidURL(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		args []string
		want string
	}{
		{name: "javascript", args: []string{"--html-url", "javascript:alert(1)"}, want: "unsupported scheme"},
		{name: "missing host", args: []string{"--debug-url", "https:///missing-host"}, want: "missing host"},
		{name: "malformed", args: []string{"--html-url", "https://[::1"}, want: "missing ']'"},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), tt.args, strings.NewReader(""), &stdout, &stderr)
			if code != 1 {
				t.Fatalf("exit code: got %d, want 1", code)
			}
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error: got %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestRunReportStepSummary_InvalidInputAndUsage(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		args     []string
		input    string
		wantCode int
		wantErr  string
	}{
		{name: "invalid JSON", input: "not json", wantCode: 1, wantErr: "decode job_result_log"},
		{name: "unknown flag", args: []string{"--bogus"}, wantCode: 2, wantErr: "flag provided but not defined"},
		{name: "too many args", args: []string{"extra"}, wantCode: 2, wantErr: "too many arguments"},
	}
	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var stdout, stderr bytes.Buffer
			code, err := runReportStepSummary(context.Background(), tt.args, strings.NewReader(tt.input), &stdout, &stderr)
			if code != tt.wantCode {
				t.Fatalf("exit code: got %d, want %d", code, tt.wantCode)
			}
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Fatalf("error: got %v, want containing %q", err, tt.wantErr)
			}
		})
	}
}

func TestRunReportStepSummary_Help(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	code, err := runReportStepSummary(context.Background(), []string{"-h"}, nil, &stdout, &stderr)
	if err != nil {
		t.Fatalf("runReportStepSummary: got error %v, want nil", err)
	}
	if code != 0 {
		t.Fatalf("exit code: got %d, want 0", code)
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout: got %q, want empty", stdout.String())
	}
	for _, want := range []string{
		"usage: cicd-sensorctl report stepsummary [flags]",
		"--html-url",
		"--debug-url",
		"--health-failed",
	} {
		if !strings.Contains(stderr.String(), want) {
			t.Fatalf("stderr: got %q, want substring %q", stderr.String(), want)
		}
	}
}
