// CollectorService ingests compressed log batches from agents.
// The manager treats payload bytes as opaque and fans them out to configured
// destinations without buffering or parsing records.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cicd_sensor/manager/v1beta1/collector.proto

package managerv1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CollectorServiceName is the fully-qualified name of the CollectorService service.
	CollectorServiceName = "cicd_sensor.manager.v1beta1.CollectorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CollectorServiceIngestLogProcedure is the fully-qualified name of the CollectorService's
	// IngestLog RPC.
	CollectorServiceIngestLogProcedure = "/cicd_sensor.manager.v1beta1.CollectorService/IngestLog"
)

// CollectorServiceClient is a client for the cicd_sensor.manager.v1beta1.CollectorService service.
type CollectorServiceClient interface {
	IngestLog(context.Context, *connect.Request[v1beta1.IngestLogRequest]) (*connect.Response[v1beta1.IngestLogResponse], error)
}

// NewCollectorServiceClient constructs a client for the
// cicd_sensor.manager.v1beta1.CollectorService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCollectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CollectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	collectorServiceMethods := v1beta1.File_cicd_sensor_manager_v1beta1_collector_proto.Services().ByName("CollectorService").Methods()
	return &collectorServiceClient{
		ingestLog: connect.NewClient[v1beta1.IngestLogRequest, v1beta1.IngestLogResponse](
			httpClient,
			baseURL+CollectorServiceIngestLogProcedure,
			connect.WithSchema(collectorServiceMethods.ByName("IngestLog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// collectorServiceClient implements CollectorServiceClient.
type collectorServiceClient struct {
	ingestLog *connect.Client[v1beta1.IngestLogRequest, v1beta1.IngestLogResponse]
}

// IngestLog calls cicd_sensor.manager.v1beta1.CollectorService.IngestLog.
func (c *collectorServiceClient) IngestLog(ctx context.Context, req *connect.Request[v1beta1.IngestLogRequest]) (*connect.Response[v1beta1.IngestLogResponse], error) {
	return c.ingestLog.CallUnary(ctx, req)
}

// CollectorServiceHandler is an implementation of the cicd_sensor.manager.v1beta1.CollectorService
// service.
type CollectorServiceHandler interface {
	IngestLog(context.Context, *connect.Request[v1beta1.IngestLogRequest]) (*connect.Response[v1beta1.IngestLogResponse], error)
}

// NewCollectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCollectorServiceHandler(svc CollectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	collectorServiceMethods := v1beta1.File_cicd_sensor_manager_v1beta1_collector_proto.Services().ByName("CollectorService").Methods()
	collectorServiceIngestLogHandler := connect.NewUnaryHandler(
		CollectorServiceIngestLogProcedure,
		svc.IngestLog,
		connect.WithSchema(collectorServiceMethods.ByName("IngestLog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cicd_sensor.manager.v1beta1.CollectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CollectorServiceIngestLogProcedure:
			collectorServiceIngestLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCollectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCollectorServiceHandler struct{}

func (UnimplementedCollectorServiceHandler) IngestLog(context.Context, *connect.Request[v1beta1.IngestLogRequest]) (*connect.Response[v1beta1.IngestLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cicd_sensor.manager.v1beta1.CollectorService.IngestLog is not implemented"))
}
