// ConfigService distributes rule/output config to host and project scopes.
// Manager is stateless: every call authenticates and returns a fresh bundle.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cicd_sensor/manager/v1beta1/config.proto

package managerv1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/cicd-sensor/cicd-sensor/internal/proto/cicd_sensor/manager/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigServiceName is the fully-qualified name of the ConfigService service.
	ConfigServiceName = "cicd_sensor.manager.v1beta1.ConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigServiceFetchConfigProcedure is the fully-qualified name of the ConfigService's FetchConfig
	// RPC.
	ConfigServiceFetchConfigProcedure = "/cicd_sensor.manager.v1beta1.ConfigService/FetchConfig"
)

// ConfigServiceClient is a client for the cicd_sensor.manager.v1beta1.ConfigService service.
type ConfigServiceClient interface {
	// FetchConfig authenticates the caller and returns the config bundle
	// visible to that caller. The manager does not generate ResolvedRules;
	// the agent merges the returned sets/modifiers with local rule inputs.
	FetchConfig(context.Context, *connect.Request[v1beta1.FetchConfigRequest]) (*connect.Response[v1beta1.FetchConfigResponse], error)
}

// NewConfigServiceClient constructs a client for the cicd_sensor.manager.v1beta1.ConfigService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configServiceMethods := v1beta1.File_cicd_sensor_manager_v1beta1_config_proto.Services().ByName("ConfigService").Methods()
	return &configServiceClient{
		fetchConfig: connect.NewClient[v1beta1.FetchConfigRequest, v1beta1.FetchConfigResponse](
			httpClient,
			baseURL+ConfigServiceFetchConfigProcedure,
			connect.WithSchema(configServiceMethods.ByName("FetchConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configServiceClient implements ConfigServiceClient.
type configServiceClient struct {
	fetchConfig *connect.Client[v1beta1.FetchConfigRequest, v1beta1.FetchConfigResponse]
}

// FetchConfig calls cicd_sensor.manager.v1beta1.ConfigService.FetchConfig.
func (c *configServiceClient) FetchConfig(ctx context.Context, req *connect.Request[v1beta1.FetchConfigRequest]) (*connect.Response[v1beta1.FetchConfigResponse], error) {
	return c.fetchConfig.CallUnary(ctx, req)
}

// ConfigServiceHandler is an implementation of the cicd_sensor.manager.v1beta1.ConfigService
// service.
type ConfigServiceHandler interface {
	// FetchConfig authenticates the caller and returns the config bundle
	// visible to that caller. The manager does not generate ResolvedRules;
	// the agent merges the returned sets/modifiers with local rule inputs.
	FetchConfig(context.Context, *connect.Request[v1beta1.FetchConfigRequest]) (*connect.Response[v1beta1.FetchConfigResponse], error)
}

// NewConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigServiceHandler(svc ConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configServiceMethods := v1beta1.File_cicd_sensor_manager_v1beta1_config_proto.Services().ByName("ConfigService").Methods()
	configServiceFetchConfigHandler := connect.NewUnaryHandler(
		ConfigServiceFetchConfigProcedure,
		svc.FetchConfig,
		connect.WithSchema(configServiceMethods.ByName("FetchConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cicd_sensor.manager.v1beta1.ConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigServiceFetchConfigProcedure:
			configServiceFetchConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigServiceHandler struct{}

func (UnimplementedConfigServiceHandler) FetchConfig(context.Context, *connect.Request[v1beta1.FetchConfigRequest]) (*connect.Response[v1beta1.FetchConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cicd_sensor.manager.v1beta1.ConfigService.FetchConfig is not implemented"))
}
